### ISSUE TITLE
MultiLingual

### ISSUE THREAD

**Issue by gah242s** [eileenmcnaughton/nz.co.fuzion.innodbtriggers#1]
Getting an error on a multi-lingual install:

Database Error Code: Table 'civicrm.civicrm_event_en_USs_in_carts' doesn't exist, 1146
Additional Details:

Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

```
[code] => -18
[message] => DB Error: no such table
[mode] => 16
[debug_info] => SHOW CREATE TABLE civicrm_event_en_USs_in_carts [nativecode=1146 ** Table 'civicrm.civicrm_event_en_USs_in_carts' doesn't exist]
[type] => DB_Error
[user_info] => SHOW CREATE TABLE civicrm_event_en_USs_in_carts [nativecode=1146 ** Table 'civicrm.civicrm_event_en_USs_in_carts' doesn't exist]
[to_string] => [db_error: message="DB Error: no such table" code=-18 mode=callback callback=CRM_Core_Error::handle prefix="" info="SHOW CREATE TABLE civicrm_event_en_USs_in_carts [nativecode=1146 ** Table 'civicrm.civicrm_event_en_USs_in_carts' doesn't exist]"]
```

)

The table civicrm.civicrm_events_in_carts does exist, but the view civicrm.civicrm_event_en_US seems to throw it for a loop.

It shows installed after this, then running the conversion table, you get:
    {

```
"error_code": "no such table",
"sql": "ALTER TABLE civicrm.log_civicrm_batch_en_US ENGINE=INNODB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4, ADD INDEX index_id(id), ADD INDEX index_log_conn_id(log_conn_id), ADD INDEX index_log_date(log_date), MODIFY log_conn_id VARCHAR(17) [nativecode=1146 ** Table 'civicrm.log_civicrm_batch_en_US' doesn't exist]",
"tip": "add debug=1 to your API call to have more info about the error",
"is_error": 1,
"error_message": "DB Error: no such table",
"debug_information": "ALTER TABLE civicrm.log_civicrm_batch_en_US ENGINE=INNODB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4, ADD INDEX index_id(id), ADD INDEX index_log_conn_id(log_conn_id), ADD INDEX index_log_date(log_date), MODIFY log_conn_id VARCHAR(17) [nativecode=1146 ** Table 'civicrm.log_civicrm_batch_en_US' doesn't exist]"
```

}

Only a few of the log_ tables get converted. Again, this is another view, rather than a table, and seems to be related to the multilingual install.

**Comment by gah242s** [comment]
Additionally, disabling and uninstalling this extension does not seem to remove the offending error above from the system.  Additional updates to the database, by say installing the EntitySettings extension, result in the same error being generated.

**Comment by mlutfy** [comment]
I sent a pull-request to fix this: https://github.com/civicrm/civicrm-core/pull/12667

**Comment by eileenmcnaughton** [comment]
upstream pr merged to Civi .6
